version: '3.8'
services:

  postgres-service:
    container_name: postgres-service
    image: postgres:15
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: banking-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./dataset/init.sql:/docker-entrypoint-initdb.d/init.sql